services:
  db:
    image: postgres:15
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: bookstore_web

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    environment:
      DB_NAME: bookstore
      DB_USER: bookstore
      DB_PASSWORD: bookstore123
      DB_HOST: db
      DB_PORT: 5432

    depends_on:
      - db

volumes:
  postgres_data: